### ISSUE TITLE
Readme for how this works

### ISSUE THREAD

**Issue by wbnns** [skynode/blockchain-dev#1]
@skynode Heya! This sounds pretty cool. How does it work? I'll be happy to help put together a `README.md` for others if you let me know.

**Comment by skynode** [comment]
@bitcoiner Hey! Thank you for the feedback. Here's how it works:

First, start the following servers: _vanilla_http_server.py_ (named for its ordinariness), the _payments_handler.py_ and the _paywalled_server.py_ from the command line. As an example:

**~/micropayments-proxy$ python3 paywalled_server.py**

Then start the http_proxy_client.py server likewise and follow the very simple instructions on the command line. As an example:

**~/micropayments-proxy$ python3 http_proxy_client.py**

```
        1.VANILLA_SERVER
        2.PAYWALLED_SERVER
        3.QUIT
```

**[+] please select a number to continue to a server:** 

Easy! Let me know if you have any problems @bitcoiner 

Ciao!
